version: '3.5'

services:
  db-postgres:
    container_name: db-advtask 
    image: postgres:12.7-alpine
    ports:
      - 5432:5432
    environment: 
      POSTGRES_DB: advtask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - pg-network

  rabbitmq:
    image: rabbitmq:3.8.19-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-log:/var/log/rabbitmq
    networks:
        - pg-network  
      
  advancedtaskcontrol.api:
    image: ${DOCKER_REGISTRY-}advancedtaskcontrolapi
    build:
      context: .
      dockerfile: src/AdvancedTaskControl.API/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - db-postgres
      - rabbitmq
    networks:
      - pg-network

  advancedtaskcontrol.messageconsumer:
    image: ${DOCKER_REGISTRY-}advancedtaskcontrolmessageconsumer
    build:
      context: .
      dockerfile:  src/AdvancedTaskControl.MessageConsumer/Dockerfile
    ports:
      - 6000:80
      - 6001:443
    depends_on:
      - db-postgres
      - rabbitmq
      - advancedtaskcontrol.gRPCService
    networks: 
      - pg-network
      
  advancedtaskcontrol.gRPCService:
    image: ${DOCKER_REGISTRY-}advancedtaskcontrolgrpcservice
    build:
      context: .
      dockerfile: src/AdvancedTaskControl.gRPCService/Dockerfile
    ports:
      - 7000:80
      - 7001:443
    depends_on:
      - db-postgres
      - rabbitmq
    networks:
      - pg-network

volumes:
  database-data: 
  rabbitmq-data:
  rabbitmq-log:

networks:
  pg-network:
    name: custom_network

  